language: node_js
node_js:
  - "node"
  - "6"
  - "4"

cache:
  directories:
    - node_modules

before_install:
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
  - npm config set spin false
  - npm install -g bower
  - bower --version
